config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :pethistories
  resources :pets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
    root 'pets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :pets, dependent: :destroy

    def patients
        @patients = self.pets.count            
    end    
end

app/models/pet.rb
class Pet < ApplicationRecord
    belongs_to :client
    has_many :pethistories, dependent: :destroy

    def visits
        self.pethistories.count            
    end    

    def owner
        Client.find(self.client_id).name
    end

    def weight_max
       self.pethistories.map {|x| x.weight}.max 
    end

    def weight_ave
        total = self.pethistories.map {|x| x.weight}
        total.inject {|sum, ele| sum + ele}/total.size
    end

    def height_max
        self.pethistories.map {|x| x.height}.max 
     end
 
     def height_ave
         total = self.pethistories.map {|x| x.height}
         total.inject {|sum, ele| sum + ele}/total.size
     end

end

app/models/pethistory.rb
class Pethistory < ApplicationRecord
    belongs_to :pet

    def historial
        @historial = Pethistory.all
    end

    def pet_name
        @pet_name = Pet.find(self.pet_id).name
    end

    def owner
        @owner = Client.find(self.client_id).name
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.eager_load(:pets)
  end

  # GET /clients/1 or /clients/1.json
  def show
    @clients = Client.eager_load(:pets)
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Cliente registrado con éxito." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Cliente actualizado con éxito." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Cliente eliminado con éxito." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :phone, :mail)
    end
end

app/controllers/pethistories_controller.rb
class PethistoriesController < ApplicationController
  before_action :set_pethistory, only: %i[ show edit update destroy ]

  # GET /pethistories or /pethistories.json
  def index
    @pethistories = Pethistory.all
  end

  # GET /pethistories/1 or /pethistories/1.json
  def show
  end

  # GET /pethistories/new
  def new
    @pethistory = Pethistory.new
    @pets = Pet.all
  end

  # GET /pethistories/1/edit
  def edit
    @pets = Pet.all
  end

  # POST /pethistories or /pethistories.json
  def create
    @pethistory = Pethistory.new(pethistory_params)
    @pethistory.client_id = @pethistory.pet.client_id 

    respond_to do |format|
      if @pethistory.save
        format.html { redirect_to pethistory_url(@pethistory), notice: "Registro de historial creado con éxito." }
        format.json { render :show, status: :created, location: @pethistory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pethistory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pethistories/1 or /pethistories/1.json
  def update
    respond_to do |format|
      if @pethistory.update(pethistory_params)
        format.html { redirect_to pethistory_url(@pethistory), notice: "Registro de historial actualizado con éxito." }
        format.json { render :show, status: :ok, location: @pethistory }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pethistory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pethistories/1 or /pethistories/1.json
  def destroy
    @pethistory.destroy

    respond_to do |format|
      format.html { redirect_to pethistories_url, notice: "Registro de historial eliminado con éxito." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pethistory
      @pethistory = Pethistory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pethistory_params
      params.require(:pethistory).permit(:weight, :height, :diagnostic, :pet_id, :client_id)
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: %i[ show edit update destroy ]

  # GET /pets or /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1 or /pets/1.json
  def show
    @pets = Pet.all
  end

  # GET /pets/new
  def new
    @pet = Pet.new
    @clients = Client.all
  end

  # GET /pets/1/edit
  def edit
    @clients = Client.all
  end

  # POST /pets or /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to pet_url(@pet), notice: "Paciente creado con éxito." }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1 or /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to pet_url(@pet), notice: "Actualización del paciente exitosa." }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1 or /pets/1.json
  def destroy
    @pet.destroy

    respond_to do |format|
      format.html { redirect_to pets_url, notice: "Paciente eliminado con éxito." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_params
      params.require(:pet).permit(:name, :race, :date_birth, :client_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/pethistories_helper.rb
module PethistoriesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <p>
    <strong>Nombre:</strong>
    <%= client.name %>
  </p>

  <p>
    <strong>Teléfono:</strong>
    <%= client.phone %>
  </p>

  <p>
    <strong>Mail:</strong>
    <%= client.mail %>
  </p>

</div>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> no permitieron registrar al cliente:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <br>
  <div>
    <%= form.label :teléfono, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>
  <br>
  <div>
    <%= form.label :mail, style: "display: block" %>
    <%= form.text_field :mail %>
  </div>
  <br>
  <div>
    <%= form.submit value ="Registrar cliente"%>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Mostrar este cliente", @client %> |
  <%= link_to "Listado de clientes", clients_path %>
</div>

app/views/clients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Clientes</h1>
<%= link_to "Nuevo cliente", new_client_path %>
<br>
<br>

<div id="clients">
<table class="table table-light table-stripped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">Mail</th>
      <th scope="col">Teléfono</th>
      <th scope="col">Mascotas</th>
      <th scope="col">Ficha cliente</th>
    </tr>
  </thead>
  <tbody>
    <% @clients.each do |client|%>
    <tr>
        <td><%= client.id %></td>
        <td><%= client.name %></td>
        <td><%= client.mail %></td>
        <td><%= client.phone %></td>
        <td><%= client.patients %></td>
        <td><%= link_to "Ficha", client_path(client)%></td>   
    </tr>
    <% end %>  
  <tbody>
</table>
</div>

app/views/clients/new.html.erb
<h1>Nuevo cliente</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Listado de clientes", clients_path %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<div>
  <%= link_to "Editar este cliente", edit_client_path(@client) %> |
  <%= link_to "Listado de clientes", clients_path %>  
</div>
<br>
<%= button_to "Eliminar este cliente", @client, method: :delete %>
<br>
<%= render @client %>
<br>
<table class="table table-light table-stripped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre mascota</th>
      <th scope="col">Fecha de nacimiento</th>
      <th scope="col">Visitas a la veterinaria</th>
      <th scope="col">Altura máxima</th>
      <th scope="col">Peso máximo</th>
      <th scope="col">Ficha médica</th>
    </tr>
  </thead>
  <tbody>
    <% @client.pets.each do |pet|%>
    <tr>
        <td><%= pet.id %></td>
        <td><%= pet.name %></td>
        <td><%= pet.date_birth %></td>
        <td><%= pet.visits %></td>
        <td><%= pet.weight_max %></td>
        <td><%= pet.height_max%></td>
        <td><%= link_to "Ficha", pet_path(pet)%></td>   
    </tr>
    <% end %>  
  <tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Veterinario</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('Favicon.png') %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= render "shared/navbar"%>
    <div class = "container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pethistories/_form.html.erb
<%= form_with(model: pethistory) do |form| %>
  <% if pethistory.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pethistory.errors.count, "error") %> no permitieron el registro del historial:</h2>

      <ul>
        <% pethistory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :paciente, style: "display: block" %>
    <%= form.select :pet_id, options_from_collection_for_select(@pets, :id, :name) %>
  </div>
  <br>
  <div>
    <%= form.label :peso, style: "display: block" %>
    <%= form.text_field :weight %>
  </div>
  <br>
  <div>
    <%= form.label :altura, style: "display: block" %>
    <%= form.text_field :height %>
  </div>
  <br>
  <div>
    <%= form.label :diagnóstico, style: "display: block" %>
    <%= form.text_area :diagnostic %>
  </div>
  <br>
  <div>
    <%= form.submit value="Registrar historial" %>
  </div>
<% end %>

app/views/pethistories/_pethistory.html.erb
<div id="<%= dom_id pethistory %>">
  <p>
    <strong>Fecha:</strong>
    <%= pethistory.created_at %>
  </p>
  
  <p>
    <strong>Dueño:</strong>
    <%= pethistory.owner %>
  </p>
  
  <p>
    <strong>Nombre mascota:</strong>
    <%= pethistory.pet_name %>
  </p>
  <p>
    <strong>Peso:</strong>
    <%= pethistory.weight %>
  </p>
  
  <p>
    <strong>Altura:</strong>
    <%= pethistory.height %>
  </p>
  
  <p>
    <strong>Diagnóstico:</strong>
    <%= pethistory.diagnostic %>
  </p>
  
</div>

app/views/pethistories/edit.html.erb
<h1>Editar historial médico</h1>

<%= render "form", pethistory: @pethistory %>

<br>

<div>
  <%= link_to "Mostrar este historial", @pethistory %> |
  <%= link_to "Listado de historiales", pethistories_path %>
</div>

app/views/pethistories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Historial de consultas</h1>

<%= link_to "Nuevo registro de historial", new_pethistory_path %>
<br>
<br>

<table class="table table-light table-stripped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Fecha</th>
      <th scope="col">Dueño</th>
      <th scope="col">Nombre mascota</th>
      <th scope="col">Peso</th>
      <th scope="col">Altura</th>
      <th scope="col">Diagnóstico</th>
      <th scope="col">Ficha visita</th>
    </tr>
  </thead>
  <tbody>
    <% @pethistories.each do |pethistory|%>
    <tr>
        <td><%= pethistory.id %></td>
        <td><%= pethistory.created_at %></td>
        <td><%= pethistory.owner %></td>
        <td><%= pethistory.pet_name %></td>
        <td><%= pethistory.weight %></td>
        <td><%= pethistory.height %></td>
        <td><%= pethistory.diagnostic %></td>
        <td><%= link_to "Registro visita", pethistory_path(pethistory)%></td>   
           
    </tr>
    <% end %>  
  <tbody>
</table>

app/views/pethistories/new.html.erb
<h1>Nuevo registro de historial</h1>

<%= render "form", pethistory: @pethistory %>

<br>

<div>
  <%= link_to "Listado de registros de historial", pethistories_path %>
</div>

app/views/pethistories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pethistory %>

<div>
  <%= link_to "Editar este historial", edit_pethistory_path(@pethistory) %> |
  <%= link_to "Listado de historiales", pethistories_path %>
</div>
<br>
<%= button_to "Eliminar este historial", @pethistory, method: :delete %>

app/views/pets/_form.html.erb
<%= form_with(model: pet) do |form| %>
  <% if pet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pet.errors.count, "error") %> no permitieron el registro del paciente:</h2>

      <ul>
        <% pet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div>
    <%= form.label :cliente, style: "display: block" %>
    <%= form.select :client_id, options_from_collection_for_select(@clients, :id, :name) %>
  </div>
  <br>
  <div>
    <%= form.label :nombre_de_la_mascota, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <br>
  <div>
    <%= form.label :raza, style: "display: block" %>
    <%= form.text_field :race %>
  </div>
  <br>
  <div>
    <%= form.label :Fecha_de_nacimiento, style: "display: block" %>
    <%= form.date_field :date_birth %>
  </div>
  <br>
  <div>
    <%= form.submit value = "Crear ficha paciente" %>
  </div>
<% end %>

app/views/pets/_pet.html.erb
<div id="<%= dom_id pet %>">
  <p>
    <%= link_to "Historial de consultas", pethistories_path%>
  </p>
  
  <p>
    <strong>Dueño:</strong>
    <%= pet.owner %>
  </p>

  <p> 
    <strong>Nombre:</strong>
    <%= pet.name %>
  </p>

  <p>
    <strong>Raza:</strong>
    <%= pet.race %>
  </p>

  <p>
    <strong>Fecha de nacimiento:</strong>
    <%= pet.date_birth %>
  </p>

  <p>
    <strong> Visitas: </strong><%= pet.visits%>
  </p>
</div>

<br>
<br>
<table class="table table-light table-stripped">
  <thead>
    <tr>
      <th scope="col">Peso promedio</th>
      <th scope="col">Peso máximo</th>
      <th scope="col">Altura promedio</th>
      <th scope="col">Altura máxima</th>
    </tr>
  </thead>
  <tbody>
    
    <tr>
        <td><%= pet.weight_ave %></td>
        <td><%= pet.weight_max %></td>
        <td><%= pet.height_ave %></td>
        <td><%= pet.height_max %></td>
           
    </tr>
   
  <tbody>
</table>

app/views/pets/edit.html.erb
<h1>Editar paciente</h1>

<%= render "form", pet: @pet %>

<br>

<div>
  <%= link_to "Mostrar paciente", @pet %> |
  <%= link_to "Listado de pacientes", pets_path %>
</div>

app/views/pets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pacientes</h1>

<%= link_to "Nuevo paciente", new_pet_path %>
<br>
<br>
<table class="table table-light table-stripped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre mascota</th>
      <th scope="col">Dueño</th>
      <th scope="col">Raza</th>
      <th scope="col">Fecha de nacimiento</th>
      <th scope="col">Visitas a la veterinaria</th>
      <th scope="col">Ficha médica</th>
    </tr>
  </thead>
  <tbody>
    <% @pets.each do |pet|%>
    <tr>
        <td><%= pet.id %></td>
        <td><%= pet.name %></td>
        <td><%= pet.owner %></td>
        <td><%= pet.race %></td>
        <td><%= pet.date_birth %></td>
        <td><%= pet.visits %></td>
        <td><%= link_to "Ficha", pet_path(pet)%></td>  
    </tr>
    <% end %>  
  <tbody>
</table>

app/views/pets/new.html.erb
<h1>Nuevo Paciente</h1>
<br>
<%= render "form", pet: @pet %>

<br>

<div>
  <%= link_to "Volver a listado de pacientes", pets_path %>
</div>

app/views/pets/show.html.erb
<p style="color: green"><%= notice %></p>

<div>
  <%= link_to "Editar paciente", edit_pet_path(@pet) %> |
  <%= link_to "Listado de pacientes", pets_path %>
  
</div>
<br>
<%= button_to "Eliminar paciente", @pet, method: :delete %>
<br>
<%= render @pet %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/pets">Registro Veterinaria</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item mx-3">
          <%= link_to "Clientes", "/clients", class:"link_navbar"%>
        </li>
        <li class="nav-item mx-3">
          <%= link_to "Pacientes", "/pets", class:"link_navbar"%>
        </li>
                <li class="nav-item mx-3">
          <%= link_to "Historial pacientes", "/pethistories", class:"link_navbar"%>
        </li>

      </ul>
    </div>
</nav>